runtime: python27
api_version: 1
threadsafe: true
automatic_scaling:
  max_idle_instances: 1
  max_concurrent_requests: 60

handlers:
- url: /.*
  script: main.app

libraries:
- name: PIL
  version: "1.1.7"
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"
